### PR TITLE
Only report selection changes if text view is still first responder.

### LINKED ISSUE #1368: [iOS] Can't add link to selected text
### Expected behavior

I expect that if I select existing text in the block editor, I can add a link to that text.

### Actual behavior

If I select text in the block editor and try to add a link to it, the link is added after the text I had selected. (Tested in WPiOS and WPAndroid, and I only observe the issue in WPiOS.)

### Steps to reproduce the behavior

1. Add a paragraph block.
2. Enter text in the block.
3. Select some of the entered text.
4. Tap the link button.
5. Note that there is no Link Text prefilled. Enter a URL (and optionally, link text).
6. Close the editor and observe that the URL or linked text is added after the text you selected in step 3.

Tested on WPiOS 13.2.1.2 TestFlight beta on iPhone XS, iOS 13.1 public beta.

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1368 

This PR makes sure that no selection changes are propagated after the aztec text view is no longer the first responder. 
This way when the Link Modal interface is called and the URL input is activated (becomes the first responder) the selection change on the original Aztec content is not propagated to the link UI.

To test:
 - Open the demo app
 - Add or edit a text block, for example paragraph
 - Write some text
 - Select some of the text
 - Tap on the link button on the toolbar
 - Make sure the link text is pre-filled with the selected text

Update release notes:

- [ ] If there are user facing changes, I have added an item to `RELEASE-NOTES.txt`.

### CODE REVIEW

File: react-native-aztec/ios/RNTAztecView/RCTAztecView.swift [hunk 1]
```diff
@@ -571,6 +571,9 @@ class RCTAztecView: Aztec.TextView {
 extension RCTAztecView: UITextViewDelegate {
 
     func textViewDidChangeSelection(_ textView: UITextView) {
+        guard isFirstResponder else {
```
Comment (etoledom) [inline react-native-aztec/ios/RNTAztecView/RCTAztecView.swift]: Maybe we could add this statement to the previously existing `guard`?
Not sure if we get an advantage by having them separated.

**Comment by rachelmcr** [comment]
@etoledom That weirdness you mentioned looks like the issue reported in https://github.com/wordpress-mobile/gutenberg-mobile/issues/1161.

**Comment by etoledom** [comment]
> @etoledom That weirdness you mentioned looks like the issue reported in #1161.

@rachelmcr you are right! Looks like it's the same issue. Since it's already a separated ticket, let's 🚢 this one ✅
