### PR TITLE
FIX empty block creation on device running AOSP keyboard

### LINKED ISSUE #856: Android - Problem with the AOSP keyboard and new block creation
There is a problem on Android devices using the stock AOSP keyboard where trying to add new empty block to the editor does delete it immediately after.
Both the Inserter UI, and the Enter.Key detection on the current block, do insert the new block, and it's visible on the screen for a very short while, then it gets deleted.

The problem is on the InputFilter on Aztec that detects the Backspace pressed event, where for some reason it's fired when empty content is set to the block (AztecText component).
`sertTextFromJs` is called in this case with empty string.

This is only happening on AOSP keyboard (I guess it's visible on emulators, anyway better to fix this to be able to properly test the demo app).

Steps to repro:
- Start the demo app on emulator
- Insert a new empty para block
- Boom it gets deleted

AOSP keyaboard

### PR DESCRIPTION
**Pull request by daniloercoli**
This PR fixes #856 by making sure to check if text listeners are enabled before doing any text/block manipulating action `onEnter` or `onBackSpace`. 

In this particular case the BackSpace.Key detection code in Aztec is called when the initial empty HTML content is set to the block via `setTextFromJS`. Text listeners are disabled in this case, and those are not running, but InputFilters are not disabled.... By the way, I guess a better fix would involve changes to Aztec, but probably is easier to fix them here, since this change could also fix other potential problems in the future.

Steps to repro:

- Start the demo app on STOCK emulator (Check AOSP keyboard)
- Insert a new empty para block
- Make sure it stays on the screen

### CODE REVIEW

**Comment by mkevins** [comment]
I just tested this on Android emulator, and it works. It also fixes this: https://github.com/wordpress-mobile/gutenberg-mobile/issues/783 . 🎉

File: react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java [hunk 1]
```diff
@@ -88,21 +89,20 @@ public ReactAztecText(ThemedReactContext reactContext) {
...
-                if (shouldHandleOnBackspace) {
+                if (shouldHandleOnBackspace && !isTextChangedListenerDisabled()) {
                     String content = toHtml(false);
                     if (TextUtils.isEmpty(content)) {
                         return onBackspace();
                     }
                     else {
-                        String emptyTag = "<" + getTagName() + "></" + getTagName() + ">";
-                        if (!content.equals(emptyTag)) {
+                        if (!content.equals(mEmptyTagHTML)) {
```
Comment (mkevins) [inline react-native-aztec/android/src/main/java/org/wordpress/mobile/ReactNativeAztec/ReactAztecText.java]: I like this refactoring. This might be useful for other things.
