### PR TITLE
Issue/1851 insert captions

### LINKED ISSUE #1851: Images inserted from Media Library do not include captions previously saved in the Media Library
Note: moved from https://github.com/wordpress-mobile/WordPress-iOS/issues/13063. /hat tip @iamthomasbishop 

### Expected behavior

I expected that if I add a caption to an image in Media and save it and then insert an image into the editor that the caption will be included by default. This is how captions work in Calypso and WP Admin.

### Actual behavior

Images added to posts from the Media Library do not include captions saved for the image in the Media section.

### Steps to reproduce the behavior

1. Go to Media, upload an image, and save a caption for that image.
1. Start a new post in either editor in the app.
1. Add the image with a caption saved in the media library from step 1.
1. Check to see if a caption is created in the editor.

**Result:** captions are not included when adding images with saved captions from the media library. ([1m48s](https://cloudup.com/c_4pR13tODl))

caption-saved caption-missing-when-inserted
<sup>Tested with WPiOS 13.8.0.0 TestFlight beta on iPhone 6S iOS 13.2.3.</sup>

<sup>(internal references: 2262379-zen p4a5px-2qu-p2 cc @ChrissiePollock)</sup>

### PR DESCRIPTION
**Pull request by SergioEstevao**
Fixes #1851 

This PR adds the caption info to the Media object that is sent between the bridge and the JS code.

I also use this opportunity to add Stub image inserters for the Media Library in Android demo app to allow to test this functionality.

Gutenberg PR: https://github.com/WordPress/gutenberg/pull/21611
WP-iOS PR: https://github.com/wordpress-mobile/WordPress-iOS/pull/13903
WP-Android PR: https://github.com/wordpress-mobile/WordPress-Android/pull/11670

To test:
 - Start the demo app
 - Add an image block
 - Check that the predefined caption shows up for the Image

PR submission checklist:

- [X] I have considered adding unit tests where possible.
- [x] I have considered if this change warrants user-facing release notes and have added them to `RELEASE-NOTES.txt` if necessary.

### CODE REVIEW

File: __device-tests__/helpers/utils.js [hunk 1]
```diff
@@ -159,11 +159,28 @@ const typeString = async ( driver: wd.PromiseChainWebdriver, element: wd.Promise
...
 
+const clearTextBox = async ( driver: wd.PromiseChainWebdriver, element: wd.PromiseChainWebdriver.Element ) => {
+	await element.click();
+	let originalText = await element.text();
+	let text = originalText;
+	// We are double tapping on the text field and pressing backspace until all content is removed.
+	do {
+		originalText = await element.text();
+		const action = new wd.TouchAction( driver );
+		action.tap( { el: element, count: 2 } );
```
Comment (ceyhun) [inline __device-tests__/helpers/utils.js:176]: Why isn't a 1 time double tap not enough out of the while loop at the beginning?

Comment (SergioEstevao) [reply __device-tests__/helpers/utils.js:176]: The method is called tap, so I assumed that I need to 2 there do get a double tap...

**Comment by SergioEstevao** [comment]
> The video caption is not inserted but I guess it's not required in this case.

I actually checked on the web GB , and it's also not inserted there.

File: __device-tests__/helpers/utils.js (hunk 1 above)
Comment (ceyhun) [reply __device-tests__/helpers/utils.js:176]: Oh I meant something different. I wanted to ask if it's working like this?

```
do
- double tap text field
- delete 1 character
- double tap text field again
- delete 1 more character
- double tap text field again
- delete 1 more character
while....
```

Comment (SergioEstevao) [reply __device-tests__/helpers/utils.js:176]: I'm doing a double tap, because it selects full words, so that way the clear should be quicker.

File: android/app/src/main/java/com/gutenberg/Media.java [hunk 2]
```diff
@@ -0,0 +1,65 @@
...
+import androidx.annotation.NonNull;
+
+import org.wordpress.mobile.ReactNativeGutenbergBridge.GutenbergBridgeJS2Parent.MediaType;
+import org.wordpress.mobile.ReactNativeGutenbergBridge.GutenbergBridgeJS2Parent.RNMedia;
+import com.facebook.react.bridge.WritableMap;
+import com.facebook.react.bridge.WritableNativeMap;
+
+import java.util.Locale;
+
+public class Media implements RNMedia {
```
Comment (maxme) [inline android/app/src/main/java/com/gutenberg/Media.java:12]: I wish we had the kotlin dependency setup to reduce this to 4 LoCs :)

Comment (hypest) [reply android/app/src/main/java/com/gutenberg/Media.java:12]: https://github.com/wordpress-mobile/gutenberg-mobile/issues/2203 🤷‍♂️
